/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DramaIdRouteImport } from './routes/drama.$id'
import { Route as WatchDramaIdEpisodeIdRouteImport } from './routes/watch.$dramaId.$episodeId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DramaIdRoute = DramaIdRouteImport.update({
  id: '/drama/$id',
  path: '/drama/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchDramaIdEpisodeIdRoute = WatchDramaIdEpisodeIdRouteImport.update({
  id: '/watch/$dramaId/$episodeId',
  path: '/watch/$dramaId/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/search': typeof SearchRoute
  '/drama/$id': typeof DramaIdRoute
  '/watch/$dramaId/$episodeId': typeof WatchDramaIdEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/search': typeof SearchRoute
  '/drama/$id': typeof DramaIdRoute
  '/watch/$dramaId/$episodeId': typeof WatchDramaIdEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/search': typeof SearchRoute
  '/drama/$id': typeof DramaIdRoute
  '/watch/$dramaId/$episodeId': typeof WatchDramaIdEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/search'
    | '/drama/$id'
    | '/watch/$dramaId/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/search' | '/drama/$id' | '/watch/$dramaId/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/search'
    | '/drama/$id'
    | '/watch/$dramaId/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  SearchRoute: typeof SearchRoute
  DramaIdRoute: typeof DramaIdRoute
  WatchDramaIdEpisodeIdRoute: typeof WatchDramaIdEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drama/$id': {
      id: '/drama/$id'
      path: '/drama/$id'
      fullPath: '/drama/$id'
      preLoaderRoute: typeof DramaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$dramaId/$episodeId': {
      id: '/watch/$dramaId/$episodeId'
      path: '/watch/$dramaId/$episodeId'
      fullPath: '/watch/$dramaId/$episodeId'
      preLoaderRoute: typeof WatchDramaIdEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  SearchRoute: SearchRoute,
  DramaIdRoute: DramaIdRoute,
  WatchDramaIdEpisodeIdRoute: WatchDramaIdEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
